#!/bin/bash
cd

set +e

OFFICIAL_REPO="deb https://packages.termux.dev/apt/termux-main stable main"
SRC="$PREFIX/etc/apt/sources.list"
SRC_DIR="$PREFIX/etc/apt/sources.list.d"

fix_repo() {
    echo "[+] Fix Termux repository..."
    mkdir -p "$SRC_DIR"
    rm -f "$SRC_DIR"/* 2>/dev/null
    echo "$OFFICIAL_REPO" > "$SRC"
    rm -rf "$PREFIX/var/lib/apt/lists"/* 2>/dev/null
    apt